### PR TITLE
Export Hasura metadata

### PR DESCRIPTION
**Pull request by hasparus**
Well... YAML is a superset of JSON.
Closes https://github.com/zagrajmy/app/issues/127.

Exported, ran `docker-compose down`, `docker-compose up` and everything looks good.

### CODE REVIEW

**Comment by radowit** [comment]
We must agree on one format of metadata.
I can switch to json, it's even more readable for me, but how can I generate it with hasura-cli?
When I do
`hasura metadata export`
the output file is YAML.

**Comment by hasparus** [comment]
@radowit but this is YAML :D I pressed a button in Hasura Console UI. This is IMO the easier way to export metadata, because you probably have Console open at all times while working to query the data in GraphiQL.

**Comment by radowit** [comment]
@hasparus 
What about structure? I want to see what changes do we have, not rewrite the file every time :)

**Comment by radowit** [comment]
I've added a PR to change metadata file to JSON: https://github.com/zagrajmy/zm-backend/pull/31

**Pull request closed without merging**
